### ISSUE TITLE
Installation/running on linux

### ISSUE THREAD

**Issue by jmlundberg** [HeinrichApfelmus/hyper-haskell#16]
Hi

I tried to install hyper-haskell for the first time, on a blank ubuntu (Xubuntu 16.04.1 LTS).

```
sudo apt-get install haskell-platform
sudo apt-get install haskell-stack
sudo apt-get install nodejs
sudo apt-get install nodejs-legacy
sudo apt-get install npm
cabal update
cabal install hyper-haskell-server
sudo npm install electron@1.4.0 -g
```
Electron seems correctly installed. I can run /usr/local/lib/node_modules/electron/dist/electron, which opens an electron window asking to specify an app.

Added export PATH=$HOME/.cabal/bin:"$PATH"
Then hyper-haskel-server runs fine, with Waiting for Haskell expression (but can't be killed with ctrl-c).

`cd ~/hask/hyper-haskell-0.1.0.0`

updated Makefile to ELECTRON=/usr/local/lib/node_modules/electron/dist/electron

`make run`

All seems fine until '/usr/local/lib/node_modules/electron/dist/electron app', which I expected to open a window, but nothing happens and it also does not terminate. What did I miss?

**Comment by HeinrichApfelmus** [comment]
Not sure. Could you add debug output? Some people got it working in Linux, issue #4 .

Note that you should not run `hyper-haskell-server` separately on your own, the Electron app will manage instances of the server process, and it may be that they interfere.

**Comment by jmlundberg** [comment]
Thank you. I read issue 4 and realized that changes were made regarding this after 0.1.0.0. With the the latest version (4cbbe04*) from October 30 2016, it opens fine, so you can close this.

**Comment by HeinrichApfelmus** [comment]
Ok, glad it worked out! :smile:
