### ISSUE TITLE
Cannot bind variables with `let`

### ISSUE THREAD

**Issue by angerman** [HeinrichApfelmus/hyper-haskell#3]
```
let x = 5
```

results in

```
<hint>:3:23: error: parse error on input ‘}’
```

Using just

```
x = 5
```

results in the very helpful message:

```
<hint>:2:3: error:
    parse error on input ‘=’
    Perhaps you need a 'let' in a 'do' block?
    e.g. 'let x = 5' instead of 'x = 5'
```

:)

**Comment by homam** [comment]
Try 

``` haskell
let x = 5 in
show x
```

``` haskell
let 
  f = (* 2)
  x = 5
in
  show $ f x
```

**Comment by angerman** [comment]
Sure! That _does_ work. However, `x = 5` or `let x = 5` would be what would work in `ghci`, and I probably foolishly expected it to work in HyperHaskell as well.

**Comment by HeinrichApfelmus** [comment]
Sorry about the confusion. At the moment, only Haskell expressions (as opposed to statements) can be parsed and evaluated. Statements (e.g. `let x = …`, `x <- someIO` etc) are planned for Level β.

**Comment by HeinrichApfelmus** [comment]
As of commit 83d4963d6dfb60bbd948737f57f50946cc5e39ce , you can execute monadic statements. In particular, you can introduce new variables with `<-`, e.g.

    test <- return "haskell"

The `let` statement is not supported just yet.

**Comment by HeinrichApfelmus** [comment]
The `let` statement is now supported in version 0.2.1.0.
