### ISSUE TITLE
Embedded GHC interpreter cannot find any modules or symbols

### ISSUE THREAD

**Issue by afcady** [HeinrichApfelmus/hyper-haskell#38]
As I mentioned on #4 I had to run this differently from the instructions to get a window to show up:

```
$ make interpreter && (cd worksheets && TESTING=y exec electron ../app)
```

This produces the following output:

```
stack --stack-yaml=haskell/stack.yaml build
Setting phasers to stun... (port 14200) (ctrl-c to quit)
Waiting for Haskell expression
Got Haskell expression, evaluating
Wrote result
Waiting for Haskell expression
Got Haskell expression, evaluating
Wrote result
Waiting for Haskell expression
WontCompile [GhcError {errMsg = "<no location info>:\n    Could not find module `Csound.Base'\n    Use -v to see a list of the files searched for."}]
```

If I try to evaluate `hello`, I get a whole lot of undefined symbols:

```
<interactive>:2:1: Not in scope: `Hyper.displayIO'
<interactive>:3:1: Not in scope: `hello'
<interactive>:5:38: Not in scope: type constructor or class `IO'
<interactive>:5:41:
    Not in scope: type constructor or class `Graphic'
```

**Comment by HeinrichApfelmus** [comment]
In the "Settings" section of the worksheet, you have to set the appropriate path to the `stack.yaml` file. This path is relative to the worksheet.

**Comment by afcady** [comment]
That wasn't the problem actually.  I can't believe it, but I was actually using a version of the source from 2016.  So it still had the problems in that bug report.  Somehow I had cloned some random fork of this repo that hadn't been updated.
