### ISSUE TITLE
Could not load import 'Csound.Patch'

### ISSUE THREAD

**Issue by schell** [HeinrichApfelmus/hyper-haskell#5]
It seems that when using stack hyper-haskell doesn't know where to look for packages (or similarly I don't know where it's looking for packages). I've run `stack build csound-expression` from the `haskell/` directory before running `make run` from the project root and then opening the `Csound.hhs` worksheet. After those steps I get the error:

```
Status: Could not load imports: <no location info>: Could not find module ‘Csound.Patch’ Use -v to see a list of the files searched for.
```

![screenshot 2016-10-17 10 16 24](https://cloud.githubusercontent.com/assets/24942/19447545/ca62cad4-9452-11e6-8081-c79858462a8d.png)

**Comment by HeinrichApfelmus** [comment]
The error message indicates that the `Csound.Patch` module is missing, which is actually part of the `csound-catalog` package. I think you have to do

```
stack install csound-expression csound-catalog csound-sampler
```

from the `haskell/` directory. This will populate the (local) .stack-work cache with the appropriate packages.

(Once the example works, remember that you can use Command + . (dot) to stop the currently running evaluation.)

**Comment by schell** [comment]
Lol - what a brain fart on my part. Thanks for the tip! Happy launch!

**Comment by HeinrichApfelmus** [comment]
It happens to the best of us. :smile: Besides, I don't think it was obvious.
